name: Checking for dispatch
on:
  workflow_dispatch:
  # repository_dispatch:
  #   types: [org-workflow-bot]
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  call-worflow-2:
    uses: testing-204/.github/.github/workflows/main.yml@main
    
